<?php
?>

<ul>
    <li>Task 1</li>
    <li>Task 2</li>
    <li>Task 3</li>
</ul>
<div data-bind="scope: 'todo'">
<!-- ko template: getTemplate() --><!-- /ko -->
</div>
<script type="text/x-magento-init">
{
    "*": {
        "Magento_Ui/js/core/app": {
            "components": {
                "todo": {
                    "component": "MyShop_Todo/js/view/todo",
                    "template": "MyShop_Todo/todo",
                    "tasks": [
                        {"label": "Task A"},
                        {"label": "Task B"},
                        {"label": "Task C"}
                    ]

                }
            }
        }

    }
}
</script>
